language: python
python:
  - '3.5'
  - '3.6'

script: pytest

deploy:
  provider: pypi
  user:
    secure: Z1NJ4HXxuaTNSGAYXVy0kFoZm8IZ5edNQAZlEAB3ixUxMrf1WMaRm6/ZHVoC7DXeZPLjdoYczdCqTGJ35N2lAlz3JhoSiA4wBPQKoPnx7S0nqs+1HczzvjRwEO0TyUhArDLrYbT3g2f/iNrlTfS3ixOLUIfo1oGj6rrEwtOxcOvzXnUPaQ06IK4OLjLUMV7QfazMBxonnbA4Q184eppWx6ig8TU+uDSMbIpI5GI/18N2hE7X94AepkgxDPn6acVnFu4fQv/VX6dm14RfVTPea9UnWJdeVCpuPypVwiF7HgKdEK23eAYIIdZhwytNUozy6BCZcF2Q/HYEuX4xUFCdpHcMz9rNQotiuyoWGB8L0Piy++rPqDLHrWPFe1bMBMTyjb2doXACNtlllCl8bQT/BHjnjVCBxzldhHYB8X89S4h8XNPA0kPqNl9OomrJH3CEVybcie+g5muigDTvb67YttQNgKFOEnJZr0xVscnYlMGIUCOPBOiaY4XmOsfW4sWyLcdk2mKVQoFP3bpM2UnRwFhHt81JYvqV6L0aRy9sJ+U09+pMLlVS65y6C5zugdME67qWQ8LlwizwUsSwl9R/HC+MkTkfuS1De796eTMbzIVYrUebE3jANvsHoAYCQpxvsdsG+1MHFNIcKRHyramlRmaeptJYhbQhUpce5UEQ5iU=
  password:
    secure: HEScrNTTzpAN67SHgNIUH+Fo56K9EfAuSfnW9i3BIIo6Yf3qgFNPND1UeTDx+mMsYNo7RmCBmaqc8kzKt0j7mxsNMcQgHSvGUSdPd+RfMt9hfaRZcMPeZGKlh38TleRxsZoFAUCyGDap8CPq18xFWfSPQIxSyda3FdlfaE2SL4l4KRSh3kFWyR8p3UxRYpmjtt/NYxI3jcqR/+qzzW9IcTwQmeOh5WDdXy2kEfcsZxRIgfXQzHYjjxx9GwCRpv/NUiSDNHolOP6eacMbBriDCU1PSNX53kahCw8/WFuCT0jxFOJfAxmQ0xwFtkF4BZpwL2KPzeWommGcN1H+ogy6OgFiOwmZz3kZcYiARfhu7a4RFymr5D/529n+JhgMQRUxgkga1oPaMey6CBS74L6rLiZds1+Q3fgX9nqQ0u+hc6ior+AHIW6R/MPdoxLxsTfDrY4Qm6WT30kP9XnAxj80Ne61v736u/Sg4u92bJB1gQGuWI13bZtmNOE2zLJ0toX2GxzWP3Bn5Wqju5tiQNn+SqPTFzSDSNj8Y2XcoAYRTTHp/FgBYCvDM46HWWFbN9CVT76wwWBZSRtdoQyDinenJCrxG0EKv9dIikQEDd4VyIkqSwCHjAgaY2LHlznMjTCkypagYj0xQdIa+nlBafb3Y0PAuaPPAAR5Hl3d+QY+VOU=
  on:
    tags: true
    python: '3.5'
